apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - like-db.yaml
  - post-db.yaml
  - user-db.yaml
  - like-service.yaml
  - post-service.yaml
  - user-service.yaml
