apiVersion: v1
kind: Service
metadata:
  name: tasks-svc-s18
  labels:
    app: tasks-app
spec:
  type: ClusterIP
  selector:
    app: tasks-app
  ports:
    - protocol: TCP
      port: 8116
      targetPort: 8116
