# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShipmentsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateShipment = channel.unary_unary(
                '/shipments.v1.ShipmentsService/CreateShipment',
                request_serializer=service__pb2.CreateShipmentRequest.SerializeToString,
                response_deserializer=service__pb2.CreateShipmentResponse.FromString,
                _registered_method=True)
        self.TrackShipment = channel.unary_stream(
                '/shipments.v1.ShipmentsService/TrackShipment',
                request_serializer=service__pb2.TrackShipmentRequest.SerializeToString,
                response_deserializer=service__pb2.ShipmentUpdate.FromString,
                _registered_method=True)


class ShipmentsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateShipment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackShipment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShipmentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateShipment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShipment,
                    request_deserializer=service__pb2.CreateShipmentRequest.FromString,
                    response_serializer=service__pb2.CreateShipmentResponse.SerializeToString,
            ),
            'TrackShipment': grpc.unary_stream_rpc_method_handler(
                    servicer.TrackShipment,
                    request_deserializer=service__pb2.TrackShipmentRequest.FromString,
                    response_serializer=service__pb2.ShipmentUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shipments.v1.ShipmentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shipments.v1.ShipmentsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShipmentsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateShipment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shipments.v1.ShipmentsService/CreateShipment',
            service__pb2.CreateShipmentRequest.SerializeToString,
            service__pb2.CreateShipmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackShipment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shipments.v1.ShipmentsService/TrackShipment',
            service__pb2.TrackShipmentRequest.SerializeToString,
            service__pb2.ShipmentUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
