# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0cshipments.v1\")\n\x15\x43reateShipmentRequest\x12\x10\n\x08tracking\x18\x01 \x01(\t\"6\n\x16\x43reateShipmentResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08tracking\x18\x02 \x01(\t\"4\n\x14TrackShipmentRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08tracking\x18\x02 \x01(\t\"P\n\x0eShipmentUpdate\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x10\n\x08sequence\x18\x04 \x01(\x05\x32\xc4\x01\n\x10ShipmentsService\x12[\n\x0e\x43reateShipment\x12#.shipments.v1.CreateShipmentRequest\x1a$.shipments.v1.CreateShipmentResponse\x12S\n\rTrackShipment\x12\".shipments.v1.TrackShipmentRequest\x1a\x1c.shipments.v1.ShipmentUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATESHIPMENTREQUEST']._serialized_start=31
  _globals['_CREATESHIPMENTREQUEST']._serialized_end=72
  _globals['_CREATESHIPMENTRESPONSE']._serialized_start=74
  _globals['_CREATESHIPMENTRESPONSE']._serialized_end=128
  _globals['_TRACKSHIPMENTREQUEST']._serialized_start=130
  _globals['_TRACKSHIPMENTREQUEST']._serialized_end=182
  _globals['_SHIPMENTUPDATE']._serialized_start=184
  _globals['_SHIPMENTUPDATE']._serialized_end=264
  _globals['_SHIPMENTSSERVICE']._serialized_start=267
  _globals['_SHIPMENTSSERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
